/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package br.gov.saude.esus.transport.common.api.configuracaodestino;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TipoUsoDestinoThrift implements org.apache.thrift.TEnum {
  PRODUCAO(0),
  TREINAMENTO(1);

  private final int value;

  private TipoUsoDestinoThrift(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TipoUsoDestinoThrift findByValue(int value) { 
    switch (value) {
      case 0:
        return PRODUCAO;
      case 1:
        return TREINAMENTO;
      default:
        return null;
    }
  }
}
