/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package br.gov.saude.esus.transport.common.api.configuracaodestino;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TipoInstalacaoDestinoThrift implements org.apache.thrift.TEnum {
  PRONTUARIO(0),
  CENTRALIZADOR(1),
  CENTRALIZADOR_NACIONAL(2);

  private final int value;

  private TipoInstalacaoDestinoThrift(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TipoInstalacaoDestinoThrift findByValue(int value) { 
    switch (value) {
      case 0:
        return PRONTUARIO;
      case 1:
        return CENTRALIZADOR;
      case 2:
        return CENTRALIZADOR_NACIONAL;
      default:
        return null;
    }
  }
}
